# Generated by Django 5.0.2 on 2024-07-12 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='people',
            field=models.IntegerField(default=1, max_length=2),
        ),
    ]
